apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
  storageClassName: do-block-storage
  persistentVolumeReclaimPolicy: Retain
